services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
    - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: User
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - user-service-db:/var/lib/postgresql/data

volumes:
  user-service-db:
  
