version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    # image: varunmfs/news-user-service:1.0
    container_name: app
    env_file:
    - .env
    ports:
      - 8086:8086
    depends_on:
      - postgres
    networks:
      - mongo-compass_mongo-network
    labels:
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      - "traefik.http.routers.user-service.rule=Host(`user-service.localhost`)"
      
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: userService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - user-service-db:/var/lib/postgresql/data
    networks:
      - mongo-compass_mongo-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    # volumes:
    #   - user-service-pgadmin:/var/lib/pgadmin
    networks:
      - mongo-compass_mongo-network

volumes:
  user-service-db:

networks:
  mongo-compass_mongo-network:
    external: true
  
